// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6.03.2026, 20:14:40
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Github/local-lead-prospector/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Github/local-lead-prospector/frontend/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Github/local-lead-prospector/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Github/local-lead-prospector/frontend/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Github/local-lead-prospector/frontend/app/plugins/**/*.{js,ts,mjs}","C:/Github/local-lead-prospector/frontend/app/composables/**/*.{js,ts,mjs}","C:/Github/local-lead-prospector/frontend/app/utils/**/*.{js,ts,mjs}","C:/Github/local-lead-prospector/frontend/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Github/local-lead-prospector/frontend/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Github/local-lead-prospector/frontend/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;